# Generated by Django 5.2 on 2025-04-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
