# Generated by Django 5.2 on 2025-05-04 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ciudad_latitud_ciudad_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_autoridad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='codigo_iso',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código ISO'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='latitud',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='longitud',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código ISO'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EntidadResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ciudad')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='entidades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('numero_caso', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField(max_length=2500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ciudad')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.estadocaso')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
