# Generated by Django 5.2 on 2025-05-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estadocaso_usuario_es_autoridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocaso',
            name='icono',
            field=models.CharField(blank=True, help_text="Clase CSS del ícono Bootstrap (ej: 'bi-check-circle')", max_length=100, null=True),
        ),
    ]
