# Generated by Django 5.2 on 2025-05-04 03:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_incidente_entidad_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='detalle',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
