# Generated by Django 5.2 on 2025-05-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_incidente_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
